'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property About() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("About", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Batch_Program___Beta() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Batch_Program___Beta", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_donate_LG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_donate_LG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version 2.0.0.6 (6/12/08)
        '''	- Continuous running openfile list so newly open documents won&apos;t be closed when Batch Program closes
        '''	- Added Flat Pattern only option for export
        '''	- Close drawings option working
        '''
        '''	Items not currently functioning
        '''	- Open parts list sometimes displays double on first run
        '''	- No tutorials yet
        '''	- Renaming function works, but sometimes doesn&apos;t play nice
        '''	
        '''Version 2.0.0.5 (6/07/08)
        '''	- Corrected bug that skipped exports depending on settings
        '''	- Fixed ini layer visibility and  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Changelog() As String
            Get
                Return ResourceManager.GetString("Changelog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [EXPORT SELECT OPTIONS]
        '''AUTOCAD VERSION=AutoCAD 2010
        '''CREATE AUTOCAD MECHANICAL=No
        '''USE TRANSMITTAL=No
        '''USE CUSTOMIZE=No
        '''CUSTOMIZE FILE=C:\_Vault Working Folder\Designs\Templates\Design Data\DWG-DXF\FlatPattern.xml
        '''CREATE LAYER GROUP=No
        '''PARTS ONLY=No
        '''REPLACE SPLINE=No
        '''CHORD TOLERANCE=0.001000
        '''[EXPORT PROPERTIES]
        '''SELECTED PROPERTIES=
        '''[EXPORT DESTINATION]
        '''SPACE=Model
        '''SCALING=Geometry
        '''ALL SHEETS=Yes
        '''MAPPING=MapsBest
        '''MODEL GEOMETRY ONLY=No
        '''EXPLODE DIMENSIONS=No
        '''SYMBOLS ARE BLOCKED=Yes
        '''AUTOCAD T [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dwg() As String
            Get
                Return ResourceManager.GetString("dwg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [EXPORT SELECT OPTIONS]
        '''AUTOCAD VERSION=AutoCAD 2010
        '''CREATE AUTOCAD MECHANICAL=No
        '''USE TRANSMITTAL=No
        '''USE CUSTOMIZE=No
        '''CUSTOMIZE FILE=C:\_Vault Working Folder\Designs\Templates\Design Data\DWG-DXF\FlatPattern.xml
        '''CREATE LAYER GROUP=No
        '''PARTS ONLY=No
        '''REPLACE SPLINE=No
        '''CHORD TOLERANCE=0.001000
        '''[EXPORT PROPERTIES]
        '''SELECTED PROPERTIES=
        '''[EXPORT DESTINATION]
        '''SPACE=Model
        '''SCALING=Geometry
        '''ALL SHEETS=Yes
        '''MAPPING=MapsBest
        '''MODEL GEOMETRY ONLY=No
        '''EXPLODE DIMENSIONS=No
        '''SYMBOLS ARE BLOCKED=Yes
        '''AUTOCAD T [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DXF() As String
            Get
                Return ResourceManager.GetString("DXF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attribute VB_Name = &quot;Get64BitPicture&quot;
        '''Public Sub Thumbnail()
        '''Dim FSO As Object, TmpFolder As Object
        '''Set FSO = CreateObject(&quot;scripting.filesystemobject&quot;)
        '''Set TmpFolder = FSO.GetSpecialFolder(2)
        '''Dim strFilename As String: strFilename = TmpFolder &amp; &quot;\PartSource.txt&quot;
        '''Dim strTextLine As String
        '''Dim iFile As Integer: iFile = FreeFile
        '''        Open strFilename For Input As #iFile
        '''Do Until EOF(1)
        '''        Line Input #1, strTextLine
        '''Loop
        '''        Close #iFile
        '''&apos; Get the active document.
        '''Dim doc As Document        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Get64BitPicture() As String
            Get
                Return ResourceManager.GetString("Get64BitPicture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inverse1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inverse1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property List_Blank() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("List_Blank", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Quote_Blank() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Quote_Blank", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Rename() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Rename", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
